CREATE TABLE EMP
AS SELECT * FROM EMPLOYEES;

-- AÑADIR COLUMNAS A UNA TABLA

ALTER TABLE EMP 
ADD DESCRIPTION VARCHAR2(1000);

-- MODIFICAR COLUMNAS A UNA TABLA

ALTER TABLE EMP
MODIFY EMAIL VARCHAR2(10);

DESC EMP

-- ELIMINAR COLUMNAS DE UNA TABLA

ALTER TABLE EMP
DROP COLUMN DESCRIPTION;

-- MARCAR COLUMNAS COMO NO UTILIZADAS (MUCHO MÁS RÁPIDO QUE ELIMINAR LA COLUMNA)
-- (NO HAY VUELTA ATRÁS)

ALTER TABLE EMP
SET UNUSED COLUMN JOB_ID;

DESC EMP

-- ELIMINAR REALMENTE LAS COLUMNAS NO UTILIZADAS

ALTER TABLE EMP
DROP UNUSED COLUMNS;


