--FORZAR LA CREACIÓN DE LA VISTA AUNQUE CONTENGA ERRORES

CREATE OR REPLACE FORCE VIEW VISTA1
AS SELECT * 
FROM TABLA_QUE_NO_EXISTE;

DESC VISTA1

-- VER LOS ERRORES DE LA VISTA

SHOW ERRORS VIEW VISTA1

-- OTRA MANERA DE VER LOS ERRORES (EN EL DICICONARIO DE DATOS ORACLE)

DESC USER_ERRORS

SELECT NAME, TYPE, TEXT 
FROM USER_ERRORS
WHERE TYPE='VIEW'
AND NAME = 'VISTA1';

-- COMPROBAR EL ESTADO DE LA VISTA EN EL DICCIONARIO DE DATOS ORACLE

DESC USER_OBJECTS

SELECT STATUS 
FROM USER_OBJECTS
WHERE OBJECT_NAME='VISTA1';

-- CONSULTAR LA VISTA EN EL DICCIONARIO DE DATOS ORACLE

DESC USER_VIEWS

SELECT TEXT
FROM USER_VIEWS
WHERE VIEW_NAME='VISTA1';

-- INTENTAMOS ACCEDER A LA VISTA

SELECT * FROM VISTA1;

-- AHORA CREAMOS LA TABLA DE LA QUE DEPENDE LA VISTA

CREATE TABLE TABLA_QUE_NO_EXISTE
AS SELECT * FROM EMPLOYEES;

-- INTENTAMOS ACCEDER A LA VISTA DE NUEVO 

SELECT * FROM VISTA1;
